"""Chemical fragment descriptions for hypothesis building.

A `Fragment` names heavy-atom sites, proton groups and the couplings between
them by label, independent of any spin-system ordering. Symmetry is given as
label permutations; couplings related by symmetry form one orbit and share
one parameter. `build_model` (builder.py) turns a fragment into the refinable
natural-abundance isotopologue set.

Extension points: new site elements and isotopes (`Site.isotopes`, the
nucleus registry), bonds for topology-based coupling priors (`bonds`, kept
but not yet used by the builder), and free-form provenance notes.
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Dict, FrozenSet, Iterable, List, Mapping, Optional, Sequence, Tuple

# Spin-1/2 isotopes labelled at natural abundance, by element. Extend here or per site.
DEFAULT_LABEL_ISOTOPES: Dict[str, Tuple[str, ...]] = {"C": ("13C",), "N": ("15N",)}


@dataclass(frozen=True)
class Site:
    """A heavy-atom position. `isotopes` overrides the element default (empty: never labelled)."""
    label: str
    element: str
    isotopes: Optional[Tuple[str, ...]] = None

    def label_isotopes(self) -> Tuple[str, ...]:
        if self.isotopes is not None:
            return tuple(self.isotopes)
        return DEFAULT_LABEL_ISOTOPES.get(self.element, ())


@dataclass(frozen=True)
class ProtonGroup:
    """Magnetically equivalent protons on one site (a methyl is one group of 3)."""
    label: str
    size: int
    site: str
    exchangeable: bool = False


Pair = FrozenSet[str]


def pair(a: str, b: str) -> Pair:
    if a == b:
        raise ValueError(f"A coupling needs two different labels, got {a!r} twice.")
    return frozenset((a, b))


@dataclass
class Fragment:
    """Sites, proton groups, couplings (Hz, by label pair), symmetry generators and notes."""
    name: str
    sites: Tuple[Site, ...]
    protons: Tuple[ProtonGroup, ...]
    couplings: Dict[Pair, float] = field(default_factory=dict)
    symmetry: Tuple[Mapping[str, str], ...] = ()
    bonds: Tuple[Tuple[str, str], ...] = ()
    notes: str = ""

    def __post_init__(self):
        self.sites = tuple(self.sites)
        self.protons = tuple(self.protons)
        self.couplings = {(k if isinstance(k, frozenset) else pair(*k)): float(v) for k, v in self.couplings.items()}
        self.symmetry = tuple(dict(g) for g in self.symmetry)
        self.validate()

    # -- lookup -------------------------------------------------------------------------
    @property
    def labels(self) -> List[str]:
        return [s.label for s in self.sites] + [p.label for p in self.protons]

    def site(self, label: str) -> Site:
        return next(s for s in self.sites if s.label == label)

    def proton(self, label: str) -> ProtonGroup:
        return next(p for p in self.protons if p.label == label)

    def order(self, label: str) -> int:
        return self.labels.index(label)

    # -- symmetry -----------------------------------------------------------------------
    def group_elements(self, limit: int = 5040) -> List[Dict[str, str]]:
        """All label permutations generated by `symmetry` (identity included)."""
        labels = self.labels
        identity = tuple(labels)
        gens = [tuple(g.get(l, l) for l in labels) for g in self.symmetry]
        index = {l: i for i, l in enumerate(labels)}
        seen = {identity}
        frontier = [identity]
        while frontier:
            new = []
            for element in frontier:
                for g in gens:
                    composed = tuple(g[index[x]] for x in element)
                    if composed not in seen:
                        seen.add(composed)
                        new.append(composed)
                        if len(seen) > limit:
                            raise ValueError("Symmetry group too large.")
            frontier = new
        return [dict(zip(labels, e)) for e in seen]

    def coupling_orbits(self, elements: Optional[List[Dict[str, str]]] = None) -> Dict[Pair, Pair]:
        """Map every label pair to a canonical representative of its orbit under the full group."""
        elements = elements or self.group_elements()
        labels = self.labels
        out: Dict[Pair, Pair] = {}
        for a in range(len(labels)):
            for b in range(a + 1, len(labels)):
                p = pair(labels[a], labels[b])
                if p in out:
                    continue
                orbit = {frozenset(g[x] for x in p) for g in elements}
                rep = min(orbit, key=lambda q: sorted(self.order(x) for x in q))
                for q in orbit:
                    out[q] = rep
        return out

    def coupling(self, a: str, b: str, orbits: Optional[Dict[Pair, Pair]] = None) -> Optional[float]:
        """Coupling of a label pair, taken from any member of its orbit; None when unspecified."""
        orbits = orbits or self.coupling_orbits()
        rep = orbits[pair(a, b)]
        values = [v for k, v in self.couplings.items() if orbits[k] == rep]
        return values[0] if values else None

    def key_name(self, rep: Pair) -> str:
        a, b = sorted(rep, key=self.order)
        return f"J({a},{b})"

    # -- validation ---------------------------------------------------------------------
    def validate(self) -> None:
        labels = self.labels
        if len(set(labels)) != len(labels):
            raise ValueError(f"Fragment {self.name!r}: labels must be unique.")
        site_labels = {s.label for s in self.sites}
        for p in self.protons:
            if p.size < 1:
                raise ValueError(f"Proton group {p.label!r} needs a positive size.")
            if p.site not in site_labels:
                raise ValueError(f"Proton group {p.label!r} is attached to unknown site {p.site!r}.")
        for k in self.couplings:
            for x in k:
                if x not in labels:
                    raise ValueError(f"Coupling {sorted(k)} refers to unknown label {x!r}.")
        for a, b in self.bonds:
            if a not in site_labels or b not in site_labels:
                raise ValueError(f"Bond {a}-{b} must join two sites.")
        kinds = {s.label: ("site", s.element) for s in self.sites}
        kinds.update({p.label: ("proton", p.size) for p in self.protons})
        for g in self.symmetry:
            if sorted(g) != sorted(g.values()) or any(x not in labels for x in g):
                raise ValueError("Each symmetry generator must permute existing labels.")
            if any(kinds[x] != kinds[y] for x, y in g.items()):
                raise ValueError("Symmetry may only exchange sites of one element or proton groups of one size.")
            for p in self.protons:
                if g.get(p.site, p.site) != self.proton(g.get(p.label, p.label)).site:
                    raise ValueError("Symmetry must map each proton group onto a group on the image site.")
        orbits = self.coupling_orbits()
        for k, v in self.couplings.items():
            for k2, v2 in self.couplings.items():
                if orbits[k] == orbits[k2] and abs(v - v2) > 1e-9:
                    raise ValueError(f"Couplings {sorted(k)} and {sorted(k2)} are related by symmetry but differ.")

    # -- editing ------------------------------------------------------------------------
    def with_couplings(self, values: Mapping, name: Optional[str] = None) -> "Fragment":
        """Copy with couplings replaced or added (keys: label pairs or key names 'J(a,b)')."""
        couplings = dict(self.couplings)
        orbits = self.coupling_orbits()
        for k, v in values.items():
            if isinstance(k, str):
                a, b = k[2:-1].split(",")
                k = pair(a, b)
            k = k if isinstance(k, frozenset) else pair(*k)
            for old in [q for q in couplings if orbits[q] == orbits[k]]:
                del couplings[old]
            couplings[k] = float(v)
        return replace(self, name=name or self.name, couplings=couplings)

    def to_dict(self) -> dict:
        return {"name": self.name,
                "sites": [{"label": s.label, "element": s.element, "isotopes": s.isotopes} for s in self.sites],
                "protons": [{"label": p.label, "size": p.size, "site": p.site, "exchangeable": p.exchangeable}
                            for p in self.protons],
                "couplings": {self.key_name(k): v for k, v in self.couplings.items()},
                "symmetry": [dict(g) for g in self.symmetry], "bonds": [list(b) for b in self.bonds],
                "notes": self.notes}

    @classmethod
    def from_dict(cls, data: dict) -> "Fragment":
        sites = tuple(Site(s["label"], s["element"], tuple(s["isotopes"]) if s.get("isotopes") is not None else None)
                      for s in data["sites"])
        protons = tuple(ProtonGroup(p["label"], int(p["size"]), p["site"], bool(p.get("exchangeable", False)))
                        for p in data["protons"])
        couplings = {}
        for k, v in data.get("couplings", {}).items():
            a, b = k[2:-1].split(",")
            couplings[pair(a, b)] = float(v)
        return cls(data["name"], sites, protons, couplings, tuple(data.get("symmetry", ())),
                   tuple(tuple(b) for b in data.get("bonds", ())), data.get("notes", ""))


def orbits_under(elements: Iterable[Dict[str, str]], labels: Sequence[str]) -> List[List[str]]:
    """Partition `labels` into orbits under the given permutations (order of first appearance)."""
    elements = list(elements)
    out: List[List[str]] = []
    seen = set()
    for l in labels:
        if l in seen:
            continue
        orbit = []
        for g in elements:
            x = g.get(l, l)
            if x not in orbit:
                orbit.append(x)
        orbit.sort(key=list(labels).index)
        seen.update(orbit)
        out.append(orbit)
    return out
